### ISSUE TITLE
[BUG] Styling issues like overflow, hidden items at different screens

### ISSUE THREAD

**Issue by devhiko** [JesseOgunlaja/Task-Tracker-Next-JS#1]
Overflow y needs to be checked and app will be tested on different browsers and window sizes to prove accessibility and consistency.
![a](https://github.com/JesseOgunlaja/Task-Tracker-Next-JS/assets/99843102/d62357f3-8bd1-4255-a2c9-0ad9bdd180c5)

**Comment by JesseOgunlaja** [comment]
I'll work on that thanks for the feedback.

**Comment by JesseOgunlaja** [comment]
Like this 
![image](https://github.com/JesseOgunlaja/Task-Tracker-Next-JS/assets/130219943/a49daee7-453f-4859-8d9e-239f2616dd4c)

**Comment by JesseOgunlaja** [comment]
The reason your log in isn’t working is because I added something to the jwt and you won’t have it until you make a new account
