### ISSUE TITLE
Nav menu has grown a chin

### ISSUE THREAD

**Issue by leowilkin** [JesseOgunlaja/Task-Tracker-Next-JS#10]
Tasks page
![Screenshot 2023-08-20 at 19 29 45](https://github.com/JesseOgunlaja/Task-Tracker-Next-JS/assets/64415791/db76bc2e-0b4d-4c7e-bcec-e6dae2976a2c)

**Comment by JesseOgunlaja** [comment]
it's because the why taskmaster goes onto two lines. Ill fix that

**Comment by leowilkin** [comment]
its good now
