### ISSUE TITLE
Wonky spacing

### ISSUE THREAD

**Issue by leowilkin** [JesseOgunlaja/Task-Tracker-Next-JS#12]
![Screenshot 2023-08-20 at 19 32 29](https://github.com/JesseOgunlaja/Task-Tracker-Next-JS/assets/64415791/6f49053e-9422-4346-949c-962addc1944f)
Description for adding tasks

**Comment by JesseOgunlaja** [comment]
what do you mean by wonky

**Comment by leowilkin** [comment]
between the schedule and work

**Comment by JesseOgunlaja** [comment]
oh year fair. I probarly just put a space by accident

**Comment by JesseOgunlaja** [comment]
Yeah ended up just being an extra space. Thanks for spotting it.
