### ISSUE TITLE
Make Two Factor auth not clickable as not current active.

### ISSUE THREAD

**Issue by leowilkin** [JesseOgunlaja/Task-Tracker-Next-JS#17]
![Screenshot 2023-08-21 at 20 25 14](https://github.com/JesseOgunlaja/Task-Tracker-Next-JS/assets/64415791/3aab3529-6d3a-4950-b28a-d28256e70224)

**Comment by JesseOgunlaja** [comment]
What do you mean

**Comment by JesseOgunlaja** [comment]
If you're wondering the two factor auth works but you don't need it if you're using Google OAuth. I'll hide it for accounts registered with Google.
