### ISSUE TITLE
Change colour scheme of settings page to replicate general theme

### ISSUE THREAD

**Issue by leowilkin** [JesseOgunlaja/Task-Tracker-Next-JS#18]
![Screenshot 2023-08-21 at 20 25 50](https://github.com/JesseOgunlaja/Task-Tracker-Next-JS/assets/64415791/62b542db-79d4-4119-ae7a-30f8e64865b7)

**Comment by JesseOgunlaja** [comment]
What colour themes do you have in mind because when I change it to just the normal background it doesn't look that good.

**Comment by JesseOgunlaja** [comment]
Closed as inactive.
Can be re opened if necessary, or continued in discussions.
