### ISSUE TITLE
[FEAUTURE REQUEST]: Adding a drag & drop sort feature to task stages and other sort filters like Date, Priority (Optional)

### ISSUE THREAD

**Issue by devhiko** [JesseOgunlaja/Task-Tracker-Next-JS#2]
When a user change some task's priority, tasks can be sorted again according to that assigned priority.
Like: 
High - sth
Low - other [x] <-- drag or change priority
Medium - another 
-- after drag  or changing priority
High - other
Hight - sth
Medium - another 
so.

**Comment by JesseOgunlaja** [comment]
I'm currently working on a drag and drop for the type like to-d and in-progress, I'll also try and work for a priority order

**Comment by JesseOgunlaja** [comment]
I've implemented this, closing the issue for now
