### ISSUE TITLE
Username button does not change anything

### ISSUE THREAD

**Issue by leowilkin** [JesseOgunlaja/Task-Tracker-Next-JS#20]
- also pls Implement Hi {username} on homepage logged in screen

![Screenshot 2023-08-21 at 20 27 35](https://github.com/JesseOgunlaja/Task-Tracker-Next-JS/assets/64415791/2b61dae4-ede7-4d4d-9aab-4a9e28960d67)

**Comment by JesseOgunlaja** [comment]
Are you not able to chan her your username. Did your press submit. I'll have a look

**Comment by JesseOgunlaja** [comment]
I know the problem it's because you can't change your username if you have a Google account because you're using Google OAuth you don't need one I forgot to hide it if you're using Google. I might allow users to change it in the future I'll see.
