### ISSUE TITLE
Make the page responsive

### ISSUE THREAD

**Issue by Cohejh** [JesseOgunlaja/Task-Tracker-Next-JS#21]
While the page does work on mobile, the spacing is very dodgy on larger screens.

**Comment by Cohejh** [comment]
<img src="https://i.imgur.com/DlDBUVE.png">

If reference is needed

**Comment by JesseOgunlaja** [comment]
Yeah I agree. I was checking at home on a bigger monitor and noticed it. I'll look into it.

**Comment by JesseOgunlaja** [comment]
I've fixed that for the signed in navbar but forgot to do the same for the logged out nav bar.

**Comment by JesseOgunlaja** [comment]
![image](https://github.com/JesseOgunlaja/Task-Tracker-Next-JS/assets/130219943/da6487c7-38bd-4b2b-9581-de54eee04388)
