### ISSUE TITLE
Change the example image on the homepage.

### ISSUE THREAD

**Issue by Cohejh** [JesseOgunlaja/Task-Tracker-Next-JS#22]
<img src="https://taskmasterapp.com/_next/image?url=%2FsampleWebsite.png&w=828&q=75">

This image could be problematic, as it gives an inaccurate representation of the app.

**Comment by JesseOgunlaja** [comment]
Yeah that image was originally supposed to be a template picture before I had finished all the tasks and projects logic I'll change it to the actual image.

**Comment by JesseOgunlaja** [comment]
Changed to an actual image on the website now. Haven't pushed yet.
