### ISSUE TITLE
Bug when all projects are deleted

### ISSUE THREAD

**Issue by Cohejh** [JesseOgunlaja/Task-Tracker-Next-JS#23]
<img src="https://imgur.com/ggIgb4m.png">

Surely this "done" section should not be visible when no projects exist in the first place?

**Comment by JesseOgunlaja** [comment]
Fair enough, good suggestion. I'm gonna start fixing everything I've been busy working on this https://github.com/JesseOgunlaja/CPlusPlus. Have a look.
