### ISSUE TITLE
UI Glitch when adding a description

### ISSUE THREAD

**Issue by Cohejh** [JesseOgunlaja/Task-Tracker-Next-JS#24]
<img src="https://imgur.com/EJGYzPa.png">

When a description is not added, and the notification that warns this pops up, and then you try to create a description, a complete UI glitch happens.

**Comment by JesseOgunlaja** [comment]
Yeah I saw that you need to disable Grammarly still don't know how to fix that

**Comment by Cohejh** [comment]
> Yeah I saw that you need to disable Grammarly still don't know how to fix that

also, apologies for all the problems.

**Comment by JesseOgunlaja** [comment]
That's fine I need people to find bugs for me so I know what to fix. Since I'm kinda lazy when it comes to that.

**Comment by JesseOgunlaja** [comment]
There is a way to fix it using.
data-gramm="false"

**Comment by Cohejh** [comment]
<img src"https://imgur.com/WcD0mER">

Appears not to be fixed

**Comment by JesseOgunlaja** [comment]
What page are you /tasks or /projects/[id]. I forgot to do it in the /tasks page thanks for spotting that.

**Comment by JesseOgunlaja** [comment]
Added it to /tasks route.
