### ISSUE TITLE
leaking the Google auth client Id better to put inside env 🔴 

### ISSUE THREAD

**Issue by Abhishek765Flyfin** [JesseOgunlaja/Task-Tracker-Next-JS#31]
https://github.com/JesseOgunlaja/Task-Tracker-Next-JS/blob/53b4728a3f8eb9f261b67e5b74bffa46d1953477/components/GoogleProvider.tsx#L15C8-L15C27

**Comment by JesseOgunlaja** [comment]
They're no point in doing that because the client ID is visible when you go to the google OAuth page.
