### ISSUE TITLE
Adaptive Navbar

### ISSUE THREAD

**Issue by devhiko** [JesseOgunlaja/Task-Tracker-Next-JS#5]
When you login and click at logo, its still showing that default user page, instead it should show your credentials and login status
Steps to reproduce:
- Open website
- Login
- Click on main logo and check if you can see your username and login status
![a](https://github.com/JesseOgunlaja/Task-Tracker-Next-JS/assets/99843102/55079ec9-c768-4057-87e1-cabdda5bb9e9)

**Comment by JesseOgunlaja** [comment]
What I’ll do is that if you are logged in no matter what page you’re on the Mac bar will have a link to the home page a link to the dashboard page a link to logout and a link to settings. I have an idea for that it’ll be done soon thanks for the suggestion

**Comment by JesseOgunlaja** [comment]
Finished it along with some other things going to push changes soon
