### ISSUE TITLE
Fix contrast on creation of new task

### ISSUE THREAD

**Issue by leowilkin** [JesseOgunlaja/Task-Tracker-Next-JS#7]
The background dimming and the black background for the task creation clash and it becomes indeterminable to tell apart.

![Screenshot 2023-08-20 at 17 19 58](https://github.com/JesseOgunlaja/Task-Tracker-Next-JS/assets/64415791/baeda1a7-09a7-49d2-8457-120af6263334)

**Comment by JesseOgunlaja** [comment]
You're really giving me a run for my money here. Leo

**Comment by leowilkin** [comment]
mm. yes.

**Comment by JesseOgunlaja** [comment]
Changed this to rgba(200, 200, 200, 0.85). Pushed changes now so you can have a look. Also seeming as you're testing everything can you test out the new tasks page.

**Comment by leowilkin** [comment]
I'm going to be really annoying and say that the white doesn't suit the black theme. A lighter grey would do, but not black.

**Comment by JesseOgunlaja** [comment]
Okay I'll get a new one wait  a sec

**Comment by JesseOgunlaja** [comment]
Changed it to rgba(51, 51, 51, 0.5); dark enough to fit the dark theme but light enough to not blend in with the black.
