### ISSUE TITLE
Fix font on subtask creation.

### ISSUE THREAD

**Issue by leowilkin** [JesseOgunlaja/Task-Tracker-Next-JS#8]
Under description.

![Screenshot 2023-08-20 at 17 23 24](https://github.com/JesseOgunlaja/Task-Tracker-Next-JS/assets/64415791/40b9aa62-37d3-46b8-b024-bef2622f4077)

**Comment by JesseOgunlaja** [comment]
Do you mean the font in the description box

**Comment by leowilkin** [comment]
Yes.

**Comment by JesseOgunlaja** [comment]
Fixed pushing soon.
