### ISSUE TITLE
[UI] Change rounding

### ISSUE THREAD

**Issue by leowilkin** [JesseOgunlaja/Task-Tracker-Next-JS#9]
From a UI perspective, but rounding the buttons to at least a rounding-sm (Tailwind CSS) would be analogous with rest of design and branding.

![Screenshot 2023-08-20 at 17 24 52](https://github.com/JesseOgunlaja/Task-Tracker-Next-JS/assets/64415791/af998a5e-59ee-49eb-ba1f-8c1a74c4dae7)

**Comment by JesseOgunlaja** [comment]
You got me on that one. I've been avoiding it due to border radius not being supported with linear gradient border.

**Comment by JesseOgunlaja** [comment]
just finished that changes will be pushed soon
